figure;
plot(log(:,2),'g');
hold on;
plot(bsplinePoses(:,2),'r');
ylabel('x');
figure;
plot(log(:,3),'g');
hold on;
plot(bsplinePoses(:,3),'r');
ylabel('y');
figure;
plot(log(:,4),'g');
hold on;
plot(bsplinePoses(:,4),'r');
ylabel('z');
figure;
plot(atan2(sin(log(:,5)), cos(log(:,5))),'g');
hold on;
plot(bsplinePoses(:,5),'r');
ylabel('yaw');
figure;
plot(log(:,6),'g');
hold on;
plot(bsplinePoses(:,6),'r');
ylabel('pitch');
figure;
plot(log(:,7),'g');
hold on;
plot(bsplinePoses(:,7),'r');
ylabel('roll');
figure;
plot(log(:,8),'g');
hold on;
plot(bsplinePoses(:,8),'r');
ylabel('v_x');
figure;
plot(log(:,9),'g');
hold on;
plot(bsplinePoses(:,9),'r');
ylabel('v_y');
figure;
plot(log(:,10),'g');
hold on;
plot(bsplinePoses(:,10),'r');
ylabel('v_z');
figure;
plot(log(:,11),'g');
hold on;
plot(bsplinePoses(:,11),'r');
ylabel('\omega_x');
figure;
plot(log(:,12),'g');
hold on;
plot(bsplinePoses(:,12),'r');
ylabel('\omega_y');
figure;
plot(log(:,13),'g');
hold on;
plot(bsplinePoses(:,13),'r');
ylabel('\omega_z');
figure;
plot(log(:,14),'g');
hold on;
plot(bsplinePoses(:,14),'r');
ylabel('a_x');
figure;
plot(log(:,15),'g');
hold on;
plot(bsplinePoses(:,15),'r');
ylabel('a_y');
figure;
plot(log(:,16),'g');
hold on;
plot(bsplinePoses(:,16),'r');
ylabel('a_z');
